### ISSUE TITLE
Any update for publication?

### ISSUE THREAD

**Issue by gyubeomim** [ziweiWWANG/Event-Blob-Tracking#2]
I'm looking forward to using your awesome work asap. 

Thanks in advance!

**Comment by ziweiWWANG** [comment]
Hi there,

Thank you for your interest!

We are currently awaiting the final round of review. Are you looking to compare your work with ours in your paper? If so, could you please let us know if there is a specific deadline for your submission or your project?

Cheers,
Ziwei

**Comment by gyubeomim** [comment]
Thank you for the reply :-) 

I'm not writing a paper now to compare your results. I am asking because your paper is very impressive and I'd like to test your research in various ways.

Regards,
Gyubeom
